@extends('layouts.main')

@section('title', 'Transaksi Jurnal Kas Masuk')

@section('content')
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed mattis nulla sit amet eros semper, eget dapibus odio mollis. Sed quis mauris accumsan, fermentum nunc eu, molestie ante. Praesent a nunc eu velit mattis semper in vel nulla. Etiam eu neque vel augue aliquet sollicitudin gravida lobortis dolor. Aliquam quam urna, consectetur consequat tellus et, gravida feugiat odio. Mauris sodales convallis tellus eget vehicula. Nullam hendrerit id est in accumsan. Maecenas massa nisi, varius vitae libero et, cursus imperdiet arcu. Morbi eget tortor tristique, porta metus at, placerat justo.</p>
<p>Pellentesque ex eros, congue id aliquam ac, tempor a nulla. Pellentesque ornare urna a elit venenatis consequat eget non arcu. Proin molestie mauris quam, interdum aliquam turpis pretium ut. Aenean facilisis tincidunt enim in bibendum. Aenean eu leo ex. Nunc ullamcorper tempor lobortis. Integer sagittis nisl in nibh malesuada vulputate. Nam malesuada scelerisque dolor, a iaculis velit. Nam lobortis fermentum metus id facilisis. Morbi sit amet pharetra magna, a ultrices justo. Etiam nec sapien eget ex laoreet hendrerit id at mauris. Vivamus nisl odio, elementum sed turpis ac, vulputate sagittis diam. Cras luctus tristique felis, id sagittis magna congue et.</p>
<p>Phasellus porttitor lorem eu nisi pretium sodales. Morbi congue vehicula nisi non ullamcorper. Donec eleifend feugiat diam, a commodo eros sollicitudin ut. Nulla sagittis velit eget erat pharetra lobortis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. In egestas tortor at turpis volutpat, sit amet egestas est tristique. Donec luctus tellus et tellus semper ullamcorper. Sed purus justo, pellentesque ut turpis a, porttitor semper dui. Nunc blandit faucibus tellus eu consectetur. Maecenas sit amet tristique nunc, nec condimentum ante. Suspendisse sollicitudin lobortis fermentum. Aliquam porta rhoncus metus eu sodales.</p>
<p>Nullam sed risus ornare, facilisis turpis vitae, ultricies elit. Quisque ut cursus purus. Proin dolor metus, tincidunt ut viverra id, efficitur ut eros. Fusce molestie turpis sed nisl viverra sodales. Aliquam arcu lorem, vestibulum eget scelerisque quis, porta eu metus. Suspendisse vulputate scelerisque ultricies. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc cursus consequat sagittis. Sed iaculis arcu id massa porta hendrerit. Duis elementum urna ac egestas molestie. Duis ullamcorper feugiat ipsum. Aenean et suscipit magna. Nunc in ante vitae turpis aliquet volutpat. Nulla consequat consequat massa aliquam sagittis. Duis dignissim dignissim iaculis. Donec finibus non ligula ac gravida.</p>
<p>Sed blandit purus vitae malesuada feugiat. Pellentesque cursus quis diam in imperdiet. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque in nulla sed quam tempor tincidunt a eu odio. Proin id arcu eget lorem aliquet porta. Vestibulum a efficitur dolor. Sed enim massa, hendrerit eget velit quis, varius accumsan sem.</p>
@endsection
